### ISSUE TITLE
script gets flagged by microsoft defender 

### ISSUE THREAD

**Issue by Zaer-x** [stuartgrubb/Illuminate#1]

**Comment by digital-stu** [comment]
If you get the following message from Defender please note that this is normal behaviour. 
![Defender SmartScreen](https://github.com/stuartgrubb/Illuminate/assets/84953991/b44c4477-2907-43e4-9712-78f63e96ea95)

Defender hasn't found a virus or threat within the application, it is just a warning to say that the application is not recognised and you should be careful.

You can get past this message by clicking **More Info** then **Run anyway**.

If you receive a different message from Defender, please post a screenshot.

**Comment by digital-stu** [comment]
Found another case where Microsoft is incorrectly flagging Illuminate as a trojan.
I have submitted a sample for Microsoft to review.

In the meantime, users can either copy the code in [Illuminate.ps1](https://github.com/stuartgrubb/Illuminate/blob/main/Illuminate/Illuminate.ps1) and run it in PowerShell or use a previous release.

**Comment by digital-stu** [comment]
Defender no longer flags Illuminate as a trojan.
